add_newline = false

format = "$directory$git_branch$character"

[directory]
style = "bold blue"
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = "âˆ‘"
format = "[git](bold yellow)\\([$branch](#ff9966)\\)"

[git_status]
format = ""

[character]
success_symbol = ""
error_symbol = ""
